name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  testBash:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello TestBash!"
jobs:
  runUnitTest:
    runs-on: ubuntu-latest
    steps:
      - run: cd src/webapp/api
      - run: npm install
      - run: npm run test