name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  testBash:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello TestBash!"
  runUnitTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: cd src/webapp/api
      - run: npm ci
      - run: npm run test